#!/bin/bash

#SBATCH -p rtx-dev
#SBATCH -o myjob.o%j
#SBATCH -e myjob.e%j
#SBATCH -J stablesr
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -t 01:30:00

cd $WORK/ImageRestoration/Microsoft/Bringing-Old-Photos-Back-to-Life
conda activate microsoft
python run.py \
--input_folder ../../test_set/img_in \
--output_folder ../results \
--GPU 1 \
--with_scratch \
--HR

cd $WORK/ImageRestoration
conda activate base
python test_set/generate_test_imgs.py -r 512 -bw -i Microsoft/results/final_output -o test_set/img_preprocessed

cd $WORK/SuperSR/StableSR
conda activate stablesr
python scripts/sr_val_ddpm_text_T_vqganfin_old.py --config configs/stableSRNew/v2-finetune_text_T_512.yaml --ckpt $SCRATCH/ckpt/stablesr_000117.ckpt --vqgan_ckpt $SCRATCH/ckpt/vqgan_cfw_00011.ckpt --init-img $WORK/ImageRestoration/test_set/img_preprocessed/ --outdir $WORK/ImageRestoration/StableSR/results/ --ddpm_steps 200 --dec_w 0.5 --colorfix_type adain