#!/bin/bash

#SBATCH -p rtx-dev
#SBATCH -o myjob.o%j
#SBATCH -e myjob.e%j
#SBATCH -J stablesr
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -t 01:30:00

FN=$(basename "$0")

cd $WORK/ImageRestoration
./clean.sh

cd $WORK/ImageRestoration
source $SCRATCH/miniconda3/etc/profile.d/conda.sh
conda activate base
python test_set/generate_test_imgs.py -r 512 -bw -i test_set/img_in -o test_set/img_preprocessed${FN} -n 0 20 -b 0 20

cd $WORK/ImageRestoration/Microsoft/Bringing-Old-Photos-Back-to-Life
source $SCRATCH/miniconda3/etc/profile.d/conda.sh
conda activate microsoft
python run.py \
--input_folder ../../test_set/img_preprocessed${FN} \
--output_folder ../results${FN} \
--GPU 1 \
--with_scratch \
--HR

cd $WORK/SuperSR/StableSR
source $SCRATCH/miniconda3/etc/profile.d/conda.sh
conda activate stablesr
python scripts/sr_val_ddpm_text_T_vqganfin_old.py --config configs/stableSRNew/v2-finetune_text_T_512.yaml --ckpt $SCRATCH/ckpt/stablesr_000117.ckpt --vqgan_ckpt $SCRATCH/ckpt/vqgan_cfw_00011.ckpt \
--init-img $WORK/ImageRestoration/Microsoft/results${FN}/final_output/ \
--outdir $WORK/ImageRestoration/SuperSR/results${FN}/ --ddpm_steps 200 --dec_w 0.5 --colorfix_type adain

cp $WORK/ImageRestoration/SuperSR/results${FN}/ $WORK/ImageRestoration/final_results${FN}