#!/bin/bash

#SBATCH -p rtx
#SBATCH -o job_1.o%j
#SBATCH -e job_1.e%j
#SBATCH -J job_1
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -t 01:30:00

# Microsoft, Preprocess, GFPGAN, HAT
FN="_job_1"
BASE="${WORK}/ImageRestoration"

cd $BASE/Microsoft/Bringing-Old-Photos-Back-to-Life
source $SCRATCH/miniconda3/etc/profile.d/conda.sh
conda activate microsoft
python run.py \
--input_folder $BASE/test_set/img_in \
--output_folder $BASE/Microsoft/results${FN} \
--GPU 1 \
--with_scratch \
--HR

cd $BASE
source $SCRATCH/miniconda3/etc/profile.d/conda.sh
conda activate base
python $BASE/test_set/generate_test_imgs.py -r 512 -bw -i $BASE/Microsoft/results${FN}/final_output -o $BASE/test_set/img_preprocessed${FN} -n 0 10 20 -b 0 10 20 -d 1

cd $BASE/GFPGAN/GFPGAN
source $SCRATCH/miniconda3/etc/profile.d/conda.sh
conda activate gfpgan
python inference_gfpgan.py -i $BASE/test_set/img_preprocessed${FN} -o $BASE/GFPGAN/results${FN} -v 1.3 -s 2

cd $BASE/HAT/HAT
source $SCRATCH/miniconda3/etc/profile.d/conda.sh
conda activate hat
python hat/test.py -opt ${BASE}/HAT/HAT-S_SRx4.yml --force_yml datasets:test_1:dataroot_lq=${BASE}/GFPGAN/results${FN}/restored_imgs name=${FN}

# python hat/test.py -opt /work2/09753/ishdeshpa/frontera/ImageRestoration/HAT/HAT-S_SRx4.yml --force_yml datasets:test_1:dataroot_lq=/work2/09753/ishdeshpa/frontera/ImageRestoration/GFPGAN/results_job_1 name=_job_1

source $SCRATCH/miniconda3/etc/profile.d/conda.sh
conda activate base
mkdir $BASE/final_results/final_results${FN}
cp -r $BASE/HAT/HAT/results/${FN}/visualization/Set5 $BASE/final_results/final_results${FN}
