#!/bin/bash

#SBATCH -p rtx
#SBATCH -o myjob.o%j
#SBATCH -e myjob.e%j
#SBATCH -J job_2
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -t 01:30:00

# Microsoft, Preprocess, StableSR, HAT
FN="_job_2"
BASE="${WORK}/ImageRestoration"

cd $BASE/Microsoft/Bringing-Old-Photos-Back-to-Life
source $SCRATCH/miniconda3/etc/profile.d/conda.sh
conda activate microsoft
python run.py \
--input_folder $BASE/test_set/img_in \
--output_folder $BASE/Microsoft/results${FN} \
--GPU 1 \
--with_scratch \
--HR

cd $BASE
source $SCRATCH/miniconda3/etc/profile.d/conda.sh
conda activate base
python $BASE/test_set/generate_test_imgs.py -r 512 -bw -i $BASE/Microsoft/results${FN}/final_output -o $BASE/test_set/img_preprocessed${FN} -n 0 10 20 -b 0 10 20 -d 0.75 0.5

cd $BASE/SuperSR/StableSR
source $SCRATCH/miniconda3/etc/profile.d/conda.sh
conda activate stablesr
python scripts/sr_val_ddpm_text_T_vqganfin_old.py --config configs/stableSRNew/v2-finetune_text_T_512.yaml --ckpt $SCRATCH/ckpt/stablesr_000117.ckpt --vqgan_ckpt $SCRATCH/ckpt/vqgan_cfw_00011.ckpt \
--init-img $BASE/test_set/img_preprocessed${FN}/ \
--outdir $BASE/SuperSR/results${FN}/ --ddpm_steps 200 --dec_w 0.5 --colorfix_type adain

cd $BASE/HAT/HAT
source $SCRATCH/miniconda3/etc/profile.d/conda.sh
conda activate hat
python hat/test.py -opt ../HAT-S_SRx4.yml --force_yml datasets:test_1:dataroot_lq=$BASE/SuperSR/results${FN} name=${FN}

source $SCRATCH/miniconda3/etc/profile.d/conda.sh
conda activate base
cp -r $BASE/HAT/HAT/results/${FN}/visualization/Set5 $BASE/final_results${FN}