#!/bin/bash

#SBATCH -p rtx
#SBATCH -o job_8.o%j
#SBATCH -e job_8.e%j
#SBATCH -J job_8
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -t 01:30:00

# Preprocess, StableSR, HAT
FN="_job_8"
BASE="${WORK}/ImageRestoration"

cd $BASE
source $SCRATCH/miniconda3/etc/profile.d/conda.sh
conda activate base
python $BASE/test_set/generate_test_imgs.py -r 512 -bw -i $BASE/test_set/img_in -o $BASE/test_set/img_preprocessed${FN} -n 0 10 20 -b 0 10 20 -d 0.75 0.5

cd $BASE/SuperSR/StableSR
source $SCRATCH/miniconda3/etc/profile.d/conda.sh
conda activate stablesr
python scripts/sr_val_ddpm_text_T_vqganfin_old.py --config configs/stableSRNew/v2-finetune_text_T_512.yaml --ckpt $SCRATCH/ckpt/stablesr_000117.ckpt --vqgan_ckpt $SCRATCH/ckpt/vqgan_cfw_00011.ckpt \
--init-img $BASE/test_set/img_preprocessed${FN}/ \
--outdir $BASE/SuperSR/results${FN}/ --ddpm_steps 200 --dec_w 0.5 --colorfix_type adain

cd $BASE/HAT/HAT
source $SCRATCH/miniconda3/etc/profile.d/conda.sh
conda activate hat
python hat/test.py -opt ../HAT-S_SRx4.yml --force_yml datasets:test_1:dataroot_lq=$BASE/SuperSR/results${FN} name=${FN}

source $SCRATCH/miniconda3/etc/profile.d/conda.sh
conda activate base
mkdir -p $BASE/final_results/final_results${FN}
cp -r $BASE/HAT/HAT/results/${FN}/visualization/Set5 $BASE/final_results/final_results${FN}