#!/bin/bash

#SBATCH -p rtx
#SBATCH -o job_6.o%j
#SBATCH -e job_6.e%j
#SBATCH -J job_6
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -t 01:30:00

# Microsoft, Preprocess, StableSR, GFPGAN
FN="_job_6"
BASE="${WORK}/ImageRestoration"

cd $BASE/Microsoft/Bringing-Old-Photos-Back-to-Life
source $SCRATCH/miniconda3/etc/profile.d/conda.sh
conda activate microsoft
python run.py \
--input_folder $BASE/test_set/img_in \
--output_folder $BASE/Microsoft/results${FN} \
--GPU 1 \
--with_scratch \
--HR

cd $BASE
source $SCRATCH/miniconda3/etc/profile.d/conda.sh
conda activate base
python $BASE/test_set/generate_test_imgs.py -r 512 -bw -i $BASE/Microsoft/results${FN}/final_output -o $BASE/test_set/img_preprocessed${FN} -n 0 10 20 -b 0 10 20 -d 0.75 0.5

cd $BASE/SuperSR/StableSR
source $SCRATCH/miniconda3/etc/profile.d/conda.sh
conda activate stablesr
python scripts/sr_val_ddpm_text_T_vqganfin_old.py --config configs/stableSRNew/v2-finetune_text_T_512.yaml --ckpt $SCRATCH/ckpt/stablesr_000117.ckpt --vqgan_ckpt $SCRATCH/ckpt/vqgan_cfw_00011.ckpt \
--init-img $BASE/test_set/img_preprocessed${FN}/ \
--outdir $BASE/SuperSR/results${FN}/ --ddpm_steps 200 --dec_w 0.5 --colorfix_type adain

cd $BASE/GFPGAN/GFPGAN
source $SCRATCH/miniconda3/etc/profile.d/conda.sh
conda activate gfpgan
python inference_gfpgan.py -i $BASE/SuperSR/results${FN} -o $BASE/GFPGAN/results${FN} -v 1.3 -s 2

source $SCRATCH/miniconda3/etc/profile.d/conda.sh
conda activate base
mkdir $BASE/final_results/final_results${FN}
cp -r $BASE/GFPGAN/results${FN}/restored_imgs $BASE/final_results/final_results${FN}