#!/bin/bash

#SBATCH -p rtx
#SBATCH -o job_4.o%j
#SBATCH -e job_4.e%j
#SBATCH -J job_4
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -t 01:30:00

# Preprocess, Microsoft, GFPGAN
FN="_job_4"
BASE="${WORK}/ImageRestoration"

cd $BASE
source $SCRATCH/miniconda3/etc/profile.d/conda.sh
conda activate base
python $BASE/test_set/generate_test_imgs.py -r 512 -bw -i $BASE/test_set/img_in -o $BASE/test_set/img_preprocessed${FN} -n 0 10 20 -b 0 10 20 -d 1

cd $BASE/Microsoft/Bringing-Old-Photos-Back-to-Life
source $SCRATCH/miniconda3/etc/profile.d/conda.sh
conda activate microsoft
python run.py \
--input_folder $BASE/test_set/img_preprocessed${FN} \
--output_folder $BASE/Microsoft/results${FN} \
--GPU 1 \
--with_scratch \
# note: no HR flag

cd $BASE/GFPGAN/GFPGAN
source $SCRATCH/miniconda3/etc/profile.d/conda.sh
conda activate gfpgan
python inference_gfpgan.py -i $BASE/Microsoft/results${FN} -o $BASE/GFPGAN/results${FN} -v 1.3 -s 2

source $SCRATCH/miniconda3/etc/profile.d/conda.sh
conda activate base
cp -r $BASE/GFPGAN/results${FN} $BASE/final_results/final_results${FN}