#!/bin/bash

#SBATCH -p rtx
#SBATCH -o job_9.o%j
#SBATCH -e job_9.e%j
#SBATCH -J job_9
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -t 01:30:00

# GFPGAN
FN="_job_9_batch_3"
BASE="${WORK}/ImageRestoration"

cd $BASE/GFPGAN/GFPGAN
source $SCRATCH/miniconda3/etc/profile.d/conda.sh
conda activate gfpgan
python inference_gfpgan.py -i $BASE/test_set/img_in -o $BASE/GFPGAN/results${FN} -v 1.3 -s 2

source $SCRATCH/miniconda3/etc/profile.d/conda.sh
conda activate base
mkdir -p $BASE/final_results/final_results${FN}
cp -r $BASE/GFPGAN/results${FN}/restored_imgs $BASE/final_results/final_results${FN}