#!/bin/bash

#SBATCH -p rtx
#SBATCH -o job_10.o%j
#SBATCH -e job_10.e%j
#SBATCH -J job_10
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -t 01:30:00

# Preprocess, StableSR, GFPGAN
FN="_job_10_batch_3"
BASE="${WORK}/ImageRestoration"

cd $BASE/GFPGAN/GFPGAN
source $SCRATCH/miniconda3/etc/profile.d/conda.sh
conda activate gfpgan
python inference_gfpgan.py -i $BASE/test_set/img_in -o $BASE/GFPGAN/results${FN} -v 1.3 -s 2

cd $BASE/HAT/HAT
source $SCRATCH/miniconda3/etc/profile.d/conda.sh
conda activate hat
python hat/test.py -opt ../HAT-S_SRx4.yml --force_yml datasets:test_1:dataroot_lq=$BASE/SuperSR/results${FN} name=${FN}

source $SCRATCH/miniconda3/etc/profile.d/conda.sh
conda activate base
mkdir -p $BASE/final_results/final_results${FN}
cp -r $BASE/HAT/HAT/results/${FN}/visualization/Set5 $BASE/final_results/final_results${FN}