#!/bin/bash

#SBATCH -p rtx
#SBATCH -o myjob.o%j
#SBATCH -e myjob.e%j
#SBATCH -J stablesr
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -t 01:30:00

cd $SCRATCH/ImageRestoration/HAT
conda init
source ~/.bashrc
conda activate edt
python hat/test.py -opt options/test/HAT-S_SRx4.yml
